# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2_post3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post3',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
        migrations.DeleteModel(
            name='Post3',
        ),
    ]
